info:
    description: "CurrencyConversionRestbuilder REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "CurrencyConversionRestbuilder"
    version: v1.0
openapi: 3.0.1
components:
  schemas:
    CurrencyConversion:
      properties:
        fromCurrency:
            type: string
        fromAmount:
            format: double
            type: number
        toCurrency:
            type: string
        toAmount:
            format: double
            type: number
        companyId:
            format: int64
            type: integer
        groupId:
            format: int64
            type: integer
        userId:
            format: int64
            type: integer        
        ipAddress:
            type: string
        userAgent:
            type: string
      type: object  
paths:
  "/currencyconversion":
      post:
        operationId: postCurrencyConversion
        description: currency conversion create form fields
        requestBody:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/CurrencyConversion"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/CurrencyConversion"
        responses:
            200:
                description: ""
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CurrencyConversion"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/CurrencyConversion"
        tags: ["CurrencyConversion"]  